---

- hosts: localhost
  connection: local
  vars:
	show_version_output: |
	  Cisco IOS XE Software, Version 16.05.01b
	  Cisco IOS Software [Everest], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.5.1b, RELEASE SOFTWARE (fc1)
	  Technical Support: http://www.cisco.com/techsupport
	  Copyright (c) 1986-2017 by Cisco Systems, Inc.
	  Compiled Tue 11-Apr-17 16:41 by mcpre


	  Cisco IOS-XE software, Copyright (c) 2005-2017 by cisco Systems, Inc.
	  All rights reserved.  Certain components of Cisco IOS-XE software are
	  licensed under the GNU General Public License ("GPL") Version 2.0.  The
	  software code licensed under GPL Version 2.0 is free software that comes
	  with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
	  GPL code under the terms of GPL Version 2.0.  For more details, see the
	  documentation or "License Notice" file accompanying the IOS-XE software,
	  or the applicable URL provided on the flyer accompanying the IOS-XE
	  software.


	  ROM: IOS-XE ROMMON

	  host-172-16-1-96 uptime is 2 minutes
	  Uptime for this control processor is 3 minutes
	  System returned to ROM by reload
	  System image file is "bootflash:packages.conf"
	  Last reload reason: Reload Command



	  This product contains cryptographic features and is subject to United
	  States and local country laws governing import, export, transfer and
	  use. Delivery of Cisco cryptographic products does not imply
	  third-party authority to import, export, distribute or use encryption.
	  Importers, exporters, distributors and users are responsible for
	  compliance with U.S. and local country laws. By using this product you
	  agree to comply with applicable laws and regulations. If you are unable
	  to comply with U.S. and local laws, return this product immediately.

	  A summary of U.S. laws governing Cisco cryptographic products may be found at:
	  http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

	  If you require further assistance please contact us by sending email to
	  export@cisco.com.

	  License Level: ax
	  License Type: Default. No valid license found.
	  Next reload license Level: ax

	  cisco CSR1000V (VXE) processor (revision VXE) with 1126522K/3075K bytes of memory.
	  Processor board ID 9TKUWGKX5MO
	  2 Gigabit Ethernet interfaces
	  32768K bytes of non-volatile configuration memory.
	  3018840K bytes of physical memory.
	  7774207K bytes of virtual hard disk at bootflash:.
	  0K bytes of WebUI ODM Files at webui:.

	  Configuration register is 0x2102

  tasks:
  - name: Read in parse_genie role
	include_role:
	  name: clay584.parse_genie

  - name: Debug Genie Filter
	debug:
	  msg: "{{ show_version_output | parse_genie(command='show version', os='iosxe') }}"
	delegate_to: localhost
