---
- name: GENERATE SNMP CONFIGS USING JINJA2 - AMERICAS
  hosts: AMER
  connection: local
  gather_facts: no

  tasks:
    - name: GENERATE IOS SNMP CONFIGURATIONS
      template:
        src: ios-snmpv2.j2
        dest: "./configs/{{ inventory_hostname }}-snmp.cfg"

    - name: DEBUG AND PRINT SNMP VARIABLES
      debug:
        var: snmp_config

- name: GENERATE SNMP CONFIGS USING JINJA2 - EMEA
  hosts: EMEA
  connection: local
  gather_facts: no

  tasks:
    - name: GENERATE IOS SNMP CONFIGURATIONS
      template:
        src: nxos-snmpv2.j2
        dest: "./configs/{{ inventory_hostname }}-snmp.cfg"

    - name: DEBUG AND PRINT SNMP VARIABLES
      debug:
        var: snmp_config