---

  - name: PLAY 1 - DEPLOYING SNMP CONFIGURATIONS ON IOS
    hosts: iosxe
    connection: network_cli
    gather_facts: no

    tasks:

      - name: TASK 1 in PLAY 1 - ENSURE SNMP COMMANDS EXIST ON IOS DEVICES
        ios_config:
          commands:
            - no snmp-server community ntc-course RO
            - no snmp-server community secret RW
            - no snmp-server location NYC_HQ
            - no snmp-server contact JOHN_SMITH
          