---

  - name: PLAY 1 - DEPLOYING SNMP CONFIGURATIONS ON IOS
    hosts: iosxe
    connection: network_cli
    gather_facts: no

    tasks:

      - name: TASK 1 IN PLAY 1 - ENSURE SNMP COMMANDS EXIST ON IOS DEVICES
        ios_config:
          src: ./configs/ios-snmp.cfg
          

  - name: PLAY 2 - DEPLOYING SNMP CONFIGURATIONS ON NXOS
    hosts: nxos
    connection: network_cli
    gather_facts: no

    tasks:

      - name: TASK 1 IN PLAY 1 - ENSURE SNMP COMMANDS EXIST ON NXOS DEVICES
        nxos_config:
          src: ./configs/nxos-snmp.cfg
          